# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on 
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        data_sets: [blood.csv] 


    # Steps represent a sequence of tasks that will be executed as part of the job

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          
      - name: Download libraries
        run: |
              pip install numpy
              pip install xlsxwriter
              pip install sklearn
              pip install scipy
              

      - name: Activating...
        run: |
              cd DeepSuperLearner
              python3 example.py ${{matrix.data_sets}}
     
      - name: Upload data
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          # Artifact name
          name: all_data
          # A file, directory or wildcard pattern that describes what to upload
          path: ./results
